name: Markdown Lint

on:
  push:
    branches: ["main"]
    paths:
      - "**/*.md"
  pull_request:
    branches: ["main"]
    paths:
      - "**/*.md"

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run markdownlint
        uses: avto-dev/markdown-lint@v1
        with:
          args: "**/*.md"
          ignore: "node_modules"
